"""initial migration

Revision ID: 5f31f0cb56c6
Revises: 
Create Date: 2026-02-23 01:06:13.148936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f31f0cb56c6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('sites',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('root_url', sa.String(length=500), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_score', sa.Float(), nullable=True),
    sa.Column('last_grade', sa.String(length=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'domain', name='uq_sites_org_domain')
    )
    op.create_index('ix_sites_domain', 'sites', ['domain'], unique=False)
    op.create_index('ix_sites_organization_id', 'sites', ['organization_id'], unique=False)
    op.create_table('audits',
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('overall_grade', sa.String(length=2), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('estimated_revenue_impact', sa.Float(), nullable=True),
    sa.Column('pages_crawled', sa.Integer(), nullable=False),
    sa.Column('issues_found', sa.Integer(), nullable=False),
    sa.Column('critical_issues', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audits_created_at', 'audits', ['created_at'], unique=False)
    op.create_index('ix_audits_site_id', 'audits', ['site_id'], unique=False)
    op.create_index('ix_audits_status', 'audits', ['status'], unique=False)
    op.create_table('audit_issues',
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('impact_score', sa.Float(), nullable=False),
    sa.Column('effort_score', sa.Float(), nullable=False),
    sa.Column('affected_count', sa.Integer(), nullable=False),
    sa.Column('affected_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('documentation_url', sa.String(length=500), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ignored', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_issues_audit_id', 'audit_issues', ['audit_id'], unique=False)
    op.create_index('ix_audit_issues_category', 'audit_issues', ['category'], unique=False)
    op.create_index('ix_audit_issues_rule_id', 'audit_issues', ['rule_id'], unique=False)
    op.create_index('ix_audit_issues_severity', 'audit_issues', ['severity'], unique=False)
    op.create_table('audit_recommendations',
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('issue_id', sa.String(length=100), nullable=False),
    sa.Column('priority_rank', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('effort', sa.String(length=20), nullable=False),
    sa.Column('impact', sa.String(length=20), nullable=False),
    sa.Column('estimated_traffic_gain', sa.Float(), nullable=False),
    sa.Column('estimated_revenue_impact', sa.Float(), nullable=False),
    sa.Column('implementation_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_recommendations_audit_id', 'audit_recommendations', ['audit_id'], unique=False)
    op.create_index('ix_audit_recommendations_rank', 'audit_recommendations', ['audit_id', 'priority_rank'], unique=False)
    op.create_table('category_scores',
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(length=2), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('issues_count', sa.Integer(), nullable=False),
    sa.Column('critical_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_category_scores_audit_id', 'category_scores', ['audit_id'], unique=False)
    op.create_index('ix_category_scores_site_id_category', 'category_scores', ['site_id', 'category'], unique=False)
    op.create_table('engine_results',
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('engine_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(length=2), nullable=False),
    sa.Column('execution_time_ms', sa.Float(), nullable=False),
    sa.Column('pages_analyzed', sa.Integer(), nullable=False),
    sa.Column('issues_count', sa.Integer(), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_id', 'engine_name', name='uq_engine_results_audit_engine')
    )
    op.create_index('ix_engine_results_audit_id', 'engine_results', ['audit_id'], unique=False)
    op.create_table('pages',
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('canonical_url', sa.String(length=2000), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=200), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('meta_description', sa.String(length=2000), nullable=True),
    sa.Column('h1', sa.String(length=512), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('load_time_ms', sa.Float(), nullable=False),
    sa.Column('page_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('internal_links_count', sa.Integer(), nullable=False),
    sa.Column('external_links_count', sa.Integer(), nullable=False),
    sa.Column('images_count', sa.Integer(), nullable=False),
    sa.Column('images_missing_alt', sa.Integer(), nullable=False),
    sa.Column('is_indexable', sa.Boolean(), nullable=False),
    sa.Column('has_canonical', sa.Boolean(), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('meta_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('structured_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pages_audit_id', 'pages', ['audit_id'], unique=False)
    op.create_index('ix_pages_site_id', 'pages', ['site_id'], unique=False)
    op.create_index('ix_pages_status_code', 'pages', ['status_code'], unique=False)
    op.create_index('ix_pages_url', 'pages', ['url'], unique=False)
    op.create_table('page_issues',
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('issue_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['audit_issues.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('page_id', 'issue_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page_issues')
    op.drop_index('ix_pages_url', table_name='pages')
    op.drop_index('ix_pages_status_code', table_name='pages')
    op.drop_index('ix_pages_site_id', table_name='pages')
    op.drop_index('ix_pages_audit_id', table_name='pages')
    op.drop_table('pages')
    op.drop_index('ix_engine_results_audit_id', table_name='engine_results')
    op.drop_table('engine_results')
    op.drop_index('ix_category_scores_site_id_category', table_name='category_scores')
    op.drop_index('ix_category_scores_audit_id', table_name='category_scores')
    op.drop_table('category_scores')
    op.drop_index('ix_audit_recommendations_rank', table_name='audit_recommendations')
    op.drop_index('ix_audit_recommendations_audit_id', table_name='audit_recommendations')
    op.drop_table('audit_recommendations')
    op.drop_index('ix_audit_issues_severity', table_name='audit_issues')
    op.drop_index('ix_audit_issues_rule_id', table_name='audit_issues')
    op.drop_index('ix_audit_issues_category', table_name='audit_issues')
    op.drop_index('ix_audit_issues_audit_id', table_name='audit_issues')
    op.drop_table('audit_issues')
    op.drop_index('ix_audits_status', table_name='audits')
    op.drop_index('ix_audits_site_id', table_name='audits')
    op.drop_index('ix_audits_created_at', table_name='audits')
    op.drop_table('audits')
    op.drop_index('ix_sites_organization_id', table_name='sites')
    op.drop_index('ix_sites_domain', table_name='sites')
    op.drop_table('sites')
    op.drop_table('organizations')
    # ### end Alembic commands ###
